### ISSUE TITLE
<Tab> conflict resolution between UltiSnips and deocomplete

### ISSUE THREAD

**Issue by Atulkmr** [nims11/dotfiles#5]
I went through you vimrc hoping to learn how to tackle the tab conflict between YCM/neocomplete and ultisnips, didn't see any line which would either change the mapping from tab to some other key combination, nor any function to resolve the conflict. 

How then ? Teach me, sensei.

**Comment by nims11** [comment]
Sorry for late reply, I forgot replying earlier.

I never ran into this because of the way I use them. I use tab for ultisnip expansion, and automatic expansion for everything else when selected in the completion box.
